name: Release Wiki

on:
  push:
    paths:
      - 'wiki/**'
    branches:
      - main

jobs:
  release_plugin:
    name: Release Wiki
    runs-on: ubuntu-latest
    permissions: write-all

    strategy:
      fail-fast: false

    steps:
    - name: Trust push user
      run: git config --global --add safe.directory *

    - uses: actions/checkout@v2

    - name: Sync Wiki
      uses: joeizzard/action-wiki-sync@master
      with:
        username: pjhampton
        access_token: ${{ secrets.GITHUB_TOKEN }}
        wiki_folder: wiki
        commit_username: 'pjhampton'
        commit_email: 'pjhampton@users.noreply.github.com'
        commit_message: 'action: wiki sync'